"use client";

import { useEffect, useState, useTransition } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Loader2, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { FindingCard } from "@/components/pitcrew/finding-card";
import { PartsSourcing } from "@/components/pitcrew/parts-sourcing";
import { EmptyState } from "@/components/pitcrew/primitives";
import {
  SeverityDot,
  StatusStepper,
  VerdictBadge,
} from "@/components/pitcrew/status";
import { ServiceRecordButton } from "@/components/pitcrew/service-record";
import { TechWorkflowPanel } from "@/components/pitcrew/workflow-panels";
import { Button } from "@/components/ui/button";
import { formatUsd } from "@/lib/format";
import { bySeverity, orderTotalCents, vehicleName } from "@/lib/pitcrew-ui";
import type { RepairOrder } from "@/lib/types";
import {
  generateOrderReportAction,
  sendToCustomerAction,
} from "@/app/actions";

const loadingLabels = [
  "Reading technician notes…",
  "Assessing severity…",
  "Writing plain English…",
];

export function OrderWorkbench({ order }: { order: RepairOrder }) {
  const router = useRouter();
  const [generating, startGenerating] = useTransition();
  const [sending, startSending] = useTransition();
  const [phase, setPhase] = useState(0);

  // Rotate the loading copy while the model works, so the wait reads as
  // deliberate rather than stalled.
  useEffect(() => {
    if (!generating) return;
    const t = setInterval(
      () => setPhase((p) => Math.min(p + 1, loadingLabels.length - 1)),
      4000,
    );
    return () => clearInterval(t);
  }, [generating]);

  const findings = order.report?.findings ?? [];
  const hasReport = findings.length > 0;
  const priced = findings.filter((f) => f.priceCents > 0);

  const generate = () =>
    startGenerating(async () => {
      setPhase(0);
      const res = await generateOrderReportAction(order.id);
      if (res.ok) {
        toast.success(
          res.source === "live"
            ? "Report generated by PitCrew AI"
            : "Report ready",
        );
        router.refresh();
      } else {
        toast.error("Could not generate the report");
      }
    });

  const send = () =>
    startSending(async () => {
      const res = await sendToCustomerAction(order.id);
      if (res.ok) {
        toast.success(`Report sent to ${order.customerName}`);
        router.refresh();
      }
    });

  const canSend = hasReport && order.status === "INSPECTION_COMPLETE";

  return (
    <main className="app-container py-8">
      <Link
        href="/shop"
        className="inline-flex items-center gap-2 text-sm text-muted-foreground transition-colors duration-150 hover:text-foreground"
      >
        <ArrowLeft className="h-4 w-4" /> Back to orders
      </Link>

      <div className="mt-4 grid grid-cols-[minmax(0,1fr)_auto] items-start gap-4">
        <div className="min-w-0">
          <h1 className="text-2xl font-bold md:text-3xl">
            {vehicleName(order)}
          </h1>
          <p className="mt-1 text-sm text-muted-foreground">
            <span className="font-mono">{order.vehicle.plate}</span> ·{" "}
            <span className="tnum">
              {order.vehicle.mileage.toLocaleString("en-US")} mi
            </span>{" "}
            · {order.customerName} · {order.customerPhone}
          </p>
        </div>
        <div className="flex shrink-0 items-center gap-2">
          {/* Advisors can pull the customer's record at any point — it's how
              they answer "what did we actually do to my car?" on the phone. */}
          <ServiceRecordButton order={order} />
          <span
            title={
              hasReport
                ? order.status === "INSPECTION_COMPLETE"
                  ? "Send this report for approval"
                  : "Already sent to the customer"
                : "Generate a report first"
            }
          >
            <Button disabled={!canSend || sending} onClick={send}>
              {sending ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" /> Sending…
                </>
              ) : (
                <>
                  Send to customer <ArrowRight className="h-4 w-4" />
                </>
              )}
            </Button>
          </span>
        </div>
      </div>

      <div className="mt-6 rounded-xl border border-border bg-card p-6 shadow-card">
        <StatusStepper
          status={order.status}
          interactive
          allowFuture
          detailOverrides={{
            AWAITING_APPROVAL: <TechWorkflowPanel order={order} />,
          }}
        />
      </div>

      <div className="mt-6 grid gap-6 lg:grid-cols-2">
        <section>
          <p className="label-caps">Technician notes</p>
          <div className="mt-2 min-h-72 whitespace-pre-wrap rounded-md border border-border bg-secondary/60 p-3 font-mono text-[13px] leading-relaxed text-foreground">
            {order.rawTechNotes}
          </div>
          <p className="mt-3 flex items-center gap-2 text-[13px] text-muted-foreground">
            {generating ? (
              <>
                <Loader2 className="h-3.5 w-3.5 animate-spin text-primary" />
                {loadingLabels[phase]}
              </>
            ) : (
              <>
                <Sparkles className="h-3.5 w-3.5 text-primary" />
                PitCrew AI writes the customer report from these notes.
              </>
            )}
          </p>
        </section>

        <section>
          <div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3">
            <p className="label-caps">Customer report</p>
            {hasReport && order.report && (
              <div className="flex items-center gap-2">
                <VerdictBadge verdict={order.report.verdict} size="sm" />
                <Button
                  variant="ghost"
                  size="sm"
                  disabled={generating}
                  onClick={generate}
                >
                  Regenerate
                </Button>
              </div>
            )}
          </div>
          <div className="mt-2 space-y-3">
            {!hasReport ? (
              <EmptyState
                icon={<Sparkles className="h-5 w-5" />}
                title="No report generated yet"
                description="Turn these technician notes into a customer-ready report in plain English."
                action={
                  <Button size="lg" disabled={generating} onClick={generate}>
                    {generating ? (
                      <>
                        <Loader2 className="h-4 w-4 animate-spin" />{" "}
                        {loadingLabels[phase]}
                      </>
                    ) : (
                      <>
                        <Sparkles className="h-4 w-4" /> Generate PitCrew Report
                      </>
                    )}
                  </Button>
                }
              />
            ) : (
              <>
                {order.report?.summary && (
                  <p className="rounded-lg border border-primary/25 bg-primary/5 p-4 text-sm leading-relaxed">
                    {order.report.summary}
                  </p>
                )}
                {[...findings].sort(bySeverity).map((f, i) => (
                  <FindingCard key={f.id} finding={f} mode="shop" index={i} />
                ))}
              </>
            )}
          </div>
        </section>
      </div>

      <section className="mt-8 rounded-xl border border-border bg-card shadow-card">
        <div className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 border-b border-border px-6 py-4">
          <p className="label-caps">Inspection line items</p>
        </div>
        {priced.length === 0 ? (
          <p className="px-6 py-6 text-sm text-muted-foreground">
            No billable items on this order yet.
          </p>
        ) : (
          <>
            {priced.map((f) => (
              <div
                key={f.id}
                className="border-b border-border px-6 py-3 last:border-0"
              >
                <div className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3">
                  <SeverityDot severity={f.severity} />
                  <span className="truncate text-[15px]">{f.title}</span>
                  <span className="tnum shrink-0 font-medium">
                    {formatUsd(f.priceCents)}
                  </span>
                </div>
                <PartsSourcing order={order} finding={f} />
              </div>
            ))}
            <div className="grid grid-cols-[minmax(0,1fr)_auto] gap-3 px-6 py-4">
              <span className="label-caps">Total</span>
              <span className="tnum text-lg font-bold">
                {formatUsd(orderTotalCents(order))}
              </span>
            </div>
          </>
        )}
      </section>
    </main>
  );
}
